### ISSUE TITLE
PageHeader broken in example app

### ISSUE THREAD

**Issue by franzheidl** [cloudoperators/juno#506] opened 2024-10-08 16:26 UTC
**Description**
Currently, the `PageHeader` appears to be broken in the example app: There is too much space to the right of the logo effectively pushing the application title to the right; the options (user name, log-out button) are not visible at all.

**Steps to Reproduce**
Run the example app.

**Expected Behavior**
The page header should look as designed.

**Screenshots**
![Image](https://github.com/user-attachments/assets/972fc836-5ceb-4770-93e8-b889728e2b43)

**Environment**
Any OS, any browser

**Comment by notandy** [comment] 2024-10-11 19:37
duplicate of #473 ?

**Closed** 2024-10-16 14:15 UTC
